sonar.projectKey=nicgen_komunumo
sonar.organization=nicgen

sonar.sources=backend,frontend/app,frontend/components,frontend/lib
sonar.exclusions=**/*_test.go,frontend/.next/**,frontend/node_modules/**,docs/**,backend/scripts/**

sonar.tests=backend
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=backend/coverage.out

sonar.sourceEncoding=UTF-8
