// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (
    id,
    email,
    email_canonical,
    password_hash,
    status,
    first_name,
    last_name,
    date_of_birth,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
)
`

type CreateAccountParams struct {
	ID             string
	Email          string
	EmailCanonical string
	PasswordHash   string
	Status         string
	FirstName      string
	LastName       string
	DateOfBirth    string
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.EmailCanonical,
		arg.PasswordHash,
		arg.Status,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getAccountByEmailCanonical = `-- name: GetAccountByEmailCanonical :one
SELECT id, email, email_canonical, password_hash, status, first_name, last_name, date_of_birth, created_at, updated_at, last_login_at FROM accounts WHERE email_canonical = ?1
`

func (q *Queries) GetAccountByEmailCanonical(ctx context.Context, emailCanonical string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmailCanonical, emailCanonical)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailCanonical,
		&i.PasswordHash,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, email_canonical, password_hash, status, first_name, last_name, date_of_birth, created_at, updated_at, last_login_at FROM accounts WHERE id = ?1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailCanonical,
		&i.PasswordHash,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const touchAccountLastLogin = `-- name: TouchAccountLastLogin :exec
UPDATE accounts SET last_login_at = ?1
WHERE id = ?2
`

type TouchAccountLastLoginParams struct {
	LastLoginAt sql.NullString
	ID          string
}

func (q *Queries) TouchAccountLastLogin(ctx context.Context, arg TouchAccountLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, touchAccountLastLogin, arg.LastLoginAt, arg.ID)
	return err
}

const updateAccountPasswordHash = `-- name: UpdateAccountPasswordHash :exec
UPDATE accounts SET password_hash = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdateAccountPasswordHashParams struct {
	PasswordHash string
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateAccountPasswordHash(ctx context.Context, arg UpdateAccountPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountPasswordHash, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts SET status = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdateAccountStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
