// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: associations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAssociation = `-- name: CreateAssociation :exec
INSERT INTO associations (account_id, legal_name, siren, rna, postal_code, about, logo_path, visibility)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type CreateAssociationParams struct {
	AccountID  string
	LegalName  string
	Siren      sql.NullString
	Rna        sql.NullString
	PostalCode string
	About      sql.NullString
	LogoPath   sql.NullString
	Visibility string
}

func (q *Queries) CreateAssociation(ctx context.Context, arg CreateAssociationParams) error {
	_, err := q.db.ExecContext(ctx, createAssociation,
		arg.AccountID,
		arg.LegalName,
		arg.Siren,
		arg.Rna,
		arg.PostalCode,
		arg.About,
		arg.LogoPath,
		arg.Visibility,
	)
	return err
}

const getAssociationByAccountID = `-- name: GetAssociationByAccountID :one
SELECT account_id, legal_name, siren, rna, postal_code, about, logo_path, visibility FROM associations WHERE account_id = ?1
`

func (q *Queries) GetAssociationByAccountID(ctx context.Context, accountID string) (Association, error) {
	row := q.db.QueryRowContext(ctx, getAssociationByAccountID, accountID)
	var i Association
	err := row.Scan(
		&i.AccountID,
		&i.LegalName,
		&i.Siren,
		&i.Rna,
		&i.PostalCode,
		&i.About,
		&i.LogoPath,
		&i.Visibility,
	)
	return i, err
}

const updateAssociation = `-- name: UpdateAssociation :exec
UPDATE associations
SET about       = ?1,
    logo_path   = ?2,
    postal_code = ?3,
    visibility  = ?4
WHERE account_id = ?5
`

type UpdateAssociationParams struct {
	About      sql.NullString
	LogoPath   sql.NullString
	PostalCode string
	Visibility string
	AccountID  string
}

func (q *Queries) UpdateAssociation(ctx context.Context, arg UpdateAssociationParams) error {
	_, err := q.db.ExecContext(ctx, updateAssociation,
		arg.About,
		arg.LogoPath,
		arg.PostalCode,
		arg.Visibility,
		arg.AccountID,
	)
	return err
}
