// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlc

import (
	"context"
	"database/sql"
)

const appendAuditEvent = `-- name: AppendAuditEvent :exec
INSERT INTO audit_log (
    id,
    occurred_at,
    event_type,
    account_id,
    email_hash,
    ip,
    user_agent,
    metadata
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type AppendAuditEventParams struct {
	ID         string
	OccurredAt string
	EventType  string
	AccountID  sql.NullString
	EmailHash  sql.NullString
	Ip         sql.NullString
	UserAgent  sql.NullString
	Metadata   sql.NullString
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, appendAuditEvent,
		arg.ID,
		arg.OccurredAt,
		arg.EventType,
		arg.AccountID,
		arg.EmailHash,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}
