// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package sqlc

import (
	"context"
)

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (id, member_account_id, association_account_id, role, status, joined_at)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type CreateMembershipParams struct {
	ID                   string
	MemberAccountID      string
	AssociationAccountID string
	Role                 string
	Status               string
	JoinedAt             string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createMembership,
		arg.ID,
		arg.MemberAccountID,
		arg.AssociationAccountID,
		arg.Role,
		arg.Status,
		arg.JoinedAt,
	)
	return err
}

const getMembershipByAccountIDs = `-- name: GetMembershipByAccountIDs :one
SELECT id, member_account_id, association_account_id, role, status, joined_at FROM memberships
WHERE member_account_id      = ?1
  AND association_account_id = ?2
`

type GetMembershipByAccountIDsParams struct {
	MemberAccountID      string
	AssociationAccountID string
}

func (q *Queries) GetMembershipByAccountIDs(ctx context.Context, arg GetMembershipByAccountIDsParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, getMembershipByAccountIDs, arg.MemberAccountID, arg.AssociationAccountID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.MemberAccountID,
		&i.AssociationAccountID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}
