// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMember = `-- name: CreateMember :exec
INSERT INTO members (account_id, first_name, last_name, birth_date, nickname, about_me, avatar_path, visibility)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type CreateMemberParams struct {
	AccountID  string
	FirstName  string
	LastName   string
	BirthDate  string
	Nickname   sql.NullString
	AboutMe    sql.NullString
	AvatarPath sql.NullString
	Visibility string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) error {
	_, err := q.db.ExecContext(ctx, createMember,
		arg.AccountID,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Nickname,
		arg.AboutMe,
		arg.AvatarPath,
		arg.Visibility,
	)
	return err
}

const getMemberByAccountID = `-- name: GetMemberByAccountID :one
SELECT account_id, first_name, last_name, birth_date, nickname, about_me, avatar_path, visibility FROM members WHERE account_id = ?1
`

func (q *Queries) GetMemberByAccountID(ctx context.Context, accountID string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMemberByAccountID, accountID)
	var i Member
	err := row.Scan(
		&i.AccountID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Nickname,
		&i.AboutMe,
		&i.AvatarPath,
		&i.Visibility,
	)
	return i, err
}

const updateMember = `-- name: UpdateMember :exec
UPDATE members
SET nickname    = ?1,
    about_me    = ?2,
    avatar_path = ?3,
    visibility  = ?4
WHERE account_id = ?5
`

type UpdateMemberParams struct {
	Nickname   sql.NullString
	AboutMe    sql.NullString
	AvatarPath sql.NullString
	Visibility string
	AccountID  string
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) error {
	_, err := q.db.ExecContext(ctx, updateMember,
		arg.Nickname,
		arg.AboutMe,
		arg.AvatarPath,
		arg.Visibility,
		arg.AccountID,
	)
	return err
}
