// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Account struct {
	ID             string
	Email          string
	EmailCanonical string
	PasswordHash   string
	Status         string
	FirstName      string
	LastName       string
	DateOfBirth    string
	CreatedAt      string
	UpdatedAt      string
	LastLoginAt    sql.NullString
}

type AuditLog struct {
	ID         string
	OccurredAt string
	EventType  string
	AccountID  sql.NullString
	EmailHash  sql.NullString
	Ip         sql.NullString
	UserAgent  sql.NullString
	Metadata   sql.NullString
}

type EmailVerification struct {
	ID         string
	AccountID  string
	TokenHash  string
	CreatedAt  string
	ExpiresAt  string
	ConsumedAt sql.NullString
}

type PasswordReset struct {
	ID         string
	AccountID  string
	TokenHash  string
	CreatedAt  string
	ExpiresAt  string
	ConsumedAt sql.NullString
}

type Session struct {
	ID         string
	AccountID  string
	CreatedAt  string
	ExpiresAt  string
	LastSeenAt string
	Ip         sql.NullString
	UserAgent  sql.NullString
}
