// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Account struct {
	ID             string
	Email          string
	EmailCanonical string
	PasswordHash   string
	Status         string
	Kind           string
	CreatedAt      string
	UpdatedAt      string
	LastLoginAt    sql.NullString
	DeletedAt      sql.NullString
}

type Association struct {
	AccountID  string
	LegalName  string
	Siren      sql.NullString
	Rna        sql.NullString
	PostalCode string
	About      sql.NullString
	LogoPath   sql.NullString
	Visibility string
}

type AuditLog struct {
	ID         string
	OccurredAt string
	EventType  string
	AccountID  sql.NullString
	EmailHash  sql.NullString
	Ip         sql.NullString
	UserAgent  sql.NullString
	Metadata   sql.NullString
}

type EmailVerification struct {
	ID         string
	AccountID  string
	TokenHash  string
	CreatedAt  string
	ExpiresAt  string
	ConsumedAt sql.NullString
}

type Member struct {
	AccountID  string
	FirstName  string
	LastName   string
	BirthDate  string
	Nickname   sql.NullString
	AboutMe    sql.NullString
	AvatarPath sql.NullString
	Visibility string
}

type Membership struct {
	ID                   string
	MemberAccountID      string
	AssociationAccountID string
	Role                 string
	Status               string
	JoinedAt             string
}

type PasswordReset struct {
	ID         string
	AccountID  string
	TokenHash  string
	CreatedAt  string
	ExpiresAt  string
	ConsumedAt sql.NullString
}

type Session struct {
	ID         string
	AccountID  string
	CreatedAt  string
	ExpiresAt  string
	LastSeenAt string
	Ip         sql.NullString
	UserAgent  sql.NullString
}
