// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error
	ConsumeEmailVerification(ctx context.Context, arg ConsumeEmailVerificationParams) error
	ConsumePasswordReset(ctx context.Context, arg ConsumePasswordResetParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	// Email Verification Queries
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error
	// Password Reset Queries
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error
	GetAccountByEmailCanonical(ctx context.Context, emailCanonical string) (Account, error)
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetActiveEmailVerificationByHash(ctx context.Context, arg GetActiveEmailVerificationByHashParams) (EmailVerification, error)
	GetActivePasswordResetByHash(ctx context.Context, arg GetActivePasswordResetByHashParams) (PasswordReset, error)
	RevokeActiveEmailVerificationsForAccount(ctx context.Context, arg RevokeActiveEmailVerificationsForAccountParams) error
	RevokeActivePasswordResetsForAccount(ctx context.Context, arg RevokeActivePasswordResetsForAccountParams) error
	TouchAccountLastLogin(ctx context.Context, arg TouchAccountLastLoginParams) error
	UpdateAccountPasswordHash(ctx context.Context, arg UpdateAccountPasswordHashParams) error
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error
}

var _ Querier = (*Queries)(nil)
