// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (
    id,
    account_id,
    created_at,
    expires_at,
    last_seen_at,
    ip,
    user_agent
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
`

type CreateSessionParams struct {
	ID         string
	AccountID  string
	CreatedAt  string
	ExpiresAt  string
	LastSeenAt string
	Ip         sql.NullString
	UserAgent  sql.NullString
}

// Session Queries
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const deleteAllSessionsForAccount = `-- name: DeleteAllSessionsForAccount :exec
DELETE FROM sessions WHERE account_id = ?1
`

func (q *Queries) DeleteAllSessionsForAccount(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessionsForAccount, accountID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, account_id, created_at, expires_at, last_seen_at, ip, user_agent
FROM sessions
WHERE id = ?1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const touchSessionLastSeen = `-- name: TouchSessionLastSeen :exec
UPDATE sessions SET last_seen_at = ?1 WHERE id = ?2
`

type TouchSessionLastSeenParams struct {
	LastSeenAt string
	ID         string
}

func (q *Queries) TouchSessionLastSeen(ctx context.Context, arg TouchSessionLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, touchSessionLastSeen, arg.LastSeenAt, arg.ID)
	return err
}
