// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const consumeEmailVerification = `-- name: ConsumeEmailVerification :exec
UPDATE email_verifications SET consumed_at = ?1
WHERE id = ?2 AND consumed_at IS NULL
`

type ConsumeEmailVerificationParams struct {
	ConsumedAt sql.NullString
	ID         string
}

func (q *Queries) ConsumeEmailVerification(ctx context.Context, arg ConsumeEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, consumeEmailVerification, arg.ConsumedAt, arg.ID)
	return err
}

const consumePasswordReset = `-- name: ConsumePasswordReset :exec
UPDATE password_resets SET consumed_at = ?1
WHERE id = ?2 AND consumed_at IS NULL
`

type ConsumePasswordResetParams struct {
	ConsumedAt sql.NullString
	ID         string
}

func (q *Queries) ConsumePasswordReset(ctx context.Context, arg ConsumePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, consumePasswordReset, arg.ConsumedAt, arg.ID)
	return err
}

const createEmailVerification = `-- name: CreateEmailVerification :exec

INSERT INTO email_verifications (
    id,
    account_id,
    token_hash,
    created_at,
    expires_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type CreateEmailVerificationParams struct {
	ID        string
	AccountID string
	TokenHash string
	CreatedAt string
	ExpiresAt string
}

// Email Verification Queries
func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createEmailVerification,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createPasswordReset = `-- name: CreatePasswordReset :exec

INSERT INTO password_resets (
    id,
    account_id,
    token_hash,
    created_at,
    expires_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type CreatePasswordResetParams struct {
	ID        string
	AccountID string
	TokenHash string
	CreatedAt string
	ExpiresAt string
}

// Password Reset Queries
func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getActiveEmailVerificationByHash = `-- name: GetActiveEmailVerificationByHash :one
SELECT id, account_id, token_hash, created_at, expires_at, consumed_at FROM email_verifications
WHERE token_hash = ?1
  AND consumed_at IS NULL
  AND expires_at > ?2
`

type GetActiveEmailVerificationByHashParams struct {
	TokenHash string
	NowTime   string
}

func (q *Queries) GetActiveEmailVerificationByHash(ctx context.Context, arg GetActiveEmailVerificationByHashParams) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, getActiveEmailVerificationByHash, arg.TokenHash, arg.NowTime)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getActivePasswordResetByHash = `-- name: GetActivePasswordResetByHash :one
SELECT id, account_id, token_hash, created_at, expires_at, consumed_at FROM password_resets
WHERE token_hash = ?1
  AND consumed_at IS NULL
  AND expires_at > ?2
`

type GetActivePasswordResetByHashParams struct {
	TokenHash string
	NowTime   string
}

func (q *Queries) GetActivePasswordResetByHash(ctx context.Context, arg GetActivePasswordResetByHashParams) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getActivePasswordResetByHash, arg.TokenHash, arg.NowTime)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const revokeActiveEmailVerificationsForAccount = `-- name: RevokeActiveEmailVerificationsForAccount :exec
UPDATE email_verifications SET consumed_at = ?1
WHERE account_id = ?2 AND consumed_at IS NULL
`

type RevokeActiveEmailVerificationsForAccountParams struct {
	ConsumedAt sql.NullString
	AccountID  string
}

func (q *Queries) RevokeActiveEmailVerificationsForAccount(ctx context.Context, arg RevokeActiveEmailVerificationsForAccountParams) error {
	_, err := q.db.ExecContext(ctx, revokeActiveEmailVerificationsForAccount, arg.ConsumedAt, arg.AccountID)
	return err
}

const revokeActivePasswordResetsForAccount = `-- name: RevokeActivePasswordResetsForAccount :exec
UPDATE password_resets SET consumed_at = ?1
WHERE account_id = ?2 AND consumed_at IS NULL
`

type RevokeActivePasswordResetsForAccountParams struct {
	ConsumedAt sql.NullString
	AccountID  string
}

func (q *Queries) RevokeActivePasswordResetsForAccount(ctx context.Context, arg RevokeActivePasswordResetsForAccountParams) error {
	_, err := q.db.ExecContext(ctx, revokeActivePasswordResetsForAccount, arg.ConsumedAt, arg.AccountID)
	return err
}
